pub mod actions;
pub mod atomicfile;
pub mod cli;
pub mod config;
pub mod config_write;
pub mod deadline;
pub mod debounce;
pub mod event;
pub mod hook;
pub mod ipc;
pub mod lockfile;
pub mod log;
pub mod mute;
pub mod paths;
pub mod redact;
pub mod snapshot;
pub mod snooze;
pub mod speech;
pub mod summarize;
pub mod tui;

pub type Reasons = Vec<String>;
